fixtures:
    symlinks:
      gitlab_mirrors  : "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.6.0
    forge_modules:
